name: Build and Publish to Docker Hub

on: Publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker-compose build
      - run: docker push mwinkler/toniebox-creativemanager:latest