version: "3.7"

services: 
  app:
    build: 
      dockerfile: ./src/TonieBox.Ui/Dockerfile
      context: ./
      args:
        HTTPS_PROXY: $HTTPS_PROXY
    env_file: .env
    environment: 
      - MEDIA_LIBRARY=/var/media
    ports: 
      - "5995:80"
    volumes:
      - $MEDIA_LIBRARY:/var/media
