name: Build and Publish to Docker Hub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -f .\src\TonieBox.Ui\Dockerfile -t mwinkler/toniebox-creativemanager .
      - run: docker login -u mwinkler -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker push mwinkler/toniebox-creativemanager:latest
